# Generated by Django 4.0.3 on 2022-03-09 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0010_alter_item_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
