# Generated by Django 4.0.3 on 2022-03-09 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0011_alter_item_description_alter_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
