# Generated by Django 4.0.3 on 2022-03-10 17:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0019_remove_item_owner_alter_post_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='owner',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='capstone.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='owner',
            field=models.CharField(max_length=100),
        ),
    ]
