# Generated by Django 4.0.3 on 2022-03-10 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0024_alter_item_id_alter_item_owner_alter_post_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
